global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: 'acr-qa'
    env: 'local'

scrape_configs:
  - job_name: 'acr-qa-flask'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
